#!/usr/bin/env python3
# Frontlines (working title) - generates MapCatalog.lua from OpenFront map manifests.
# Copyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.
# Based on OpenFront: (c) OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO
# Map data (c) OpenFront and Contributors, CC BY-SA 4.0.
#
# Usage: python3 gen_catalog.py [path/to/OpenFrontIO/resources/maps] > MapCatalog.lua
#        (defaults to /home/claude/ofr/resources/maps and writes MapCatalog.lua next to this script)

import json
import os
import sys

MAPS_DIR = sys.argv[1] if len(sys.argv) > 1 else "/home/claude/ofr/resources/maps"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "MapCatalog.lua")

# (module id, OpenFront folder). Order = display order. Europe ships with the game already.
MAPS = [
    ("Europe", "europe"),
    ("World", "world"),
    ("Africa", "africa"),
    ("NorthAmerica", "northamerica"),
    ("UnitedStates", "unitedstates"),
    ("Alps", "alps"),
    ("Britannia", "britannia"),
    ("Italia", "italia"),
]

MAX_DIM = 1024  # EditableImage limit per axis
SCALE = 4  # map16x is 1/4 scale per axis


def lua_str(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 32:
            out.append("\\%d" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    lines = [
        "--[[",
        "\tFrontlines (working title) - list of playable maps.",
        "\tCopyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.",
        "\tBased on OpenFront: © OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO",
        "\tMap data © OpenFront and Contributors, CC BY-SA 4.0",
        "",
        "\tGENERATED by gen_catalog.py - do not edit by hand. Terrain lives in",
        "\tReplicatedStorage.Shared.Maps.<id> (create missing ones with import_maps.luau).",
        "\tNation entries are { name, x, y, flag }: x, y are map16x tile coordinates (full-resolution",
        "\tcoordinates // 4); flag is an OpenFront flag code drawn by FlagKit (\"\" = none).",
        "]]",
        "",
        "export type MapInfo = {",
        "\tid: string,",
        "\tname: string,",
        "\tfolder: string,",
        "\twidth: number,",
        "\theight: number,",
        "\tland: number,",
        "\tnations: { { any } },",
        "}",
        "",
        "-- Plain array; the first entry is the default map.",
        "local maps: { MapInfo } = {",
    ]
    for mid, folder in MAPS:
        d = os.path.join(MAPS_DIR, folder)
        with open(os.path.join(d, "manifest.json"), encoding="utf-8") as f:
            m = json.load(f)
        w, h = m["map16x"]["width"], m["map16x"]["height"]
        assert w <= MAX_DIM and h <= MAX_DIM, (mid, w, h)
        binp = os.path.join(d, "map16x.bin")
        if os.path.exists(binp):
            assert os.path.getsize(binp) == w * h, (mid, os.path.getsize(binp), w * h)
        lines.append("\t{")
        lines.append("\t\tid = %s," % lua_str(mid))
        lines.append("\t\tname = %s," % lua_str(m["name"]))
        lines.append("\t\tfolder = %s," % lua_str(folder))
        lines.append("\t\twidth = %d," % w)
        lines.append("\t\theight = %d," % h)
        lines.append("\t\tland = %d," % m["map16x"].get("num_land_tiles", 0))
        lines.append("\t\tnations = {")
        for n in m.get("nations", []):
            x, y = n["coordinates"]
            x = min(max(int(x) // SCALE, 0), w - 1)
            y = min(max(int(y) // SCALE, 0), h - 1)
            # 4th field: OpenFront flag code (resources/flags/<code>.svg, see gen_flags.py), "" if none.
            lines.append("\t\t\t{ %s, %d, %d, %s }," % (lua_str(n["name"]), x, y, lua_str(n.get("flag") or "")))
        lines.append("\t\t},")
        lines.append("\t},")
    lines += [
        "}",
        "",
        "return maps",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote", OUT, file=sys.stderr)


if __name__ == "__main__":
    main()
