import json,re
ofr='/home/claude/ofr'
themes=json.load(open(ofr+'/resources/tribeNameThemes.json'))
cat=open('/home/claude/frontlines/rules_flow/MapCatalog.lua').read()
folders=re.findall(r'folder = "([a-z0-9]+)"',cat)
mapthemes={}
used={'default'}
for f in folders:
    try:
        info=json.load(open(f'{ofr}/map-generator/assets/maps/{f}/info.json'))
    except Exception: info={}
    t=info.get('themes') or ['default']
    mapthemes[f]=t; used.update(t)
def lua_list(xs):
    out=[];line='\t\t\t'
    for x in xs:
        s=json.dumps(x,ensure_ascii=False)+', '
        if len(line)+len(s)>100: out.append(line.rstrip()); line='\t\t\t'
        line+=s
    out.append(line.rstrip())
    return '\n'.join(out)
L=[]
L.append('''--[[
	War Front - tribe (bot) name generator.
	Copyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.
	Based on OpenFront: © OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO
	Name lists from OpenFront resources/tribeNameThemes.json, © OpenFront and Contributors, CC BY-SA 4.0.
	Modified version re-implemented in Luau for Roblox; not affiliated with or endorsed by OpenFront.
]]

-- ServerScriptService.TribeNames (ModuleScript). GENERATED by gen_tribes.py from OpenFront's
-- tribeNameThemes.json and each map's info.json "themes" (TribeSpawner.ts / utils/TribeNames.ts):
-- a tribe is named "<prefix> <suffix>" from the merged themes of the map (default theme if none).

local TribeNames = {}

-- map folder (MapCatalog .folder) -> theme keys
local MAP_THEMES = {''')
for f,t in mapthemes.items():
    L.append(f'\t{f} = {{ {", ".join(json.dumps(x) for x in t)} }},')
L.append('}\n\nlocal THEMES = {')
for k in sorted(used):
    L.append(f'\t{k} = {{\n\t\tprefixes = {{\n{lua_list(themes[k]["prefixes"])}\n\t\t}},\n\t\tsuffixes = {{\n{lua_list(themes[k]["suffixes"])}\n\t\t}},\n\t}},')
L.append('''}

-- Returns a function that yields a new tribe name each call (random prefix + suffix, like
-- TribeSpawner.randomTribeName with no custom tribes). `folder` is the map's MapCatalog folder.
function TribeNames.picker(folder: string?, rng: Random): () -> string
	local keys = (folder and MAP_THEMES[folder]) or { "default" }
	local prefixes, suffixes = {}, {}
	for _, key in keys do
		local theme = THEMES[key]
		if theme then
			table.move(theme.prefixes, 1, #theme.prefixes, #prefixes + 1, prefixes)
			table.move(theme.suffixes, 1, #theme.suffixes, #suffixes + 1, suffixes)
		end
	end
	if #prefixes == 0 or #suffixes == 0 then
		prefixes, suffixes = THEMES.default.prefixes, THEMES.default.suffixes
	end
	return function(): string
		return prefixes[rng:NextInteger(1, #prefixes)] .. " " .. suffixes[rng:NextInteger(1, #suffixes)]
	end
end

-- createRandomName (Util.ts, "Hidden Names" setting): a stable fake name for a human player,
-- "👤 <prefix> <suffix>" from the default theme, picked by simpleHash(name).
function TribeNames.anonymous(name: string): string
	local hash = 0
	for _, c in utf8.codes(name) do
		hash = (hash * 31 + c) % 4294967296
	end
	if hash >= 2147483648 then
		hash -= 4294967296 -- 32-bit signed, like JS
	end
	hash = math.abs(hash)
	local prefixes, suffixes = THEMES.default.prefixes, THEMES.default.suffixes
	local p = hash % #prefixes
	local s = (hash // #prefixes) % #suffixes
	return "👤 " .. prefixes[p + 1] .. " " .. suffixes[s + 1]
end

return TribeNames
''')
open('/home/claude/frontlines/rules_flow/TribeNames.lua','w').write('\n'.join(L))
print(mapthemes, used)
