import json
ofr='/home/claude/ofr'
qc=json.load(open(ofr+'/resources/QuickChat.json'))
en=json.load(open(ofr+'/resources/lang/en.json'))['chat']
L=['''--[[
	War Front - quick chat phrase list (shared by server validation and client menus).
	Copyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.
	Based on OpenFront: © OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO
	Phrases from OpenFront resources/QuickChat.json + resources/lang/en.json, CC BY-SA 4.0.
	Modified version re-implemented in Luau for Roblox; not affiliated with or endorsed by OpenFront.
]]

-- ReplicatedStorage.Shared.QuickChat (ModuleScript). GENERATED by gen_quickchat.py.
-- A phrase key is "<category>.<key>" (e.g. "help.troops"), exactly OpenFront's quickChatKey.
-- Phrases with requiresPlayer = true contain "[P1]", replaced by the chosen target player's name.
-- Client -> server: net:FireServer("quickChat", recipientId, phraseKey, targetId?)
-- Server -> sender and recipient: "quickChat" { from, to, key, target? }
-- Display (EventsDisplay.onDisplayChatEvent): recipient sees QuickChat.FROM, sender QuickChat.TO.

local QuickChat = {}

QuickChat.TITLE = %s
QuickChat.FROM = %s -- {user}, {msg}
QuickChat.TO = %s -- {user}, {msg}
QuickChat.COOLDOWN_TICKS = 30 -- Config.quickChatCooldown(): 3 s per recipient

-- Categories in OpenFront's menu order, with their phrases in order.
QuickChat.CATEGORIES = {''' % (json.dumps(en['title']), json.dumps(en['from']), json.dumps(en['to']))]
for cat, items in qc.items():
    L.append('\t{')
    L.append(f'\t\tkey = {json.dumps(cat)},')
    L.append(f'\t\tname = {json.dumps(en["cat"][cat], ensure_ascii=False)},')
    L.append('\t\tphrases = {')
    for it in items:
        L.append(f'\t\t\t{{ key = {json.dumps(cat+"."+it["key"])}, text = {json.dumps(en[cat][it["key"]], ensure_ascii=False)}, requiresPlayer = {str(it["requiresPlayer"]).lower()} }},')
    L.append('\t\t},')
    L.append('\t},')
L.append('''}

-- Flat lookup: phraseKey -> phrase entry.
QuickChat.BY_KEY = {}
for _, cat in QuickChat.CATEGORIES do
	for _, phrase in cat.phrases do
		QuickChat.BY_KEY[phrase.key] = phrase
	end
end

-- English text for a phrase key, with [P1] replaced by targetName.
function QuickChat.text(key: string, targetName: string?): string
	local phrase = QuickChat.BY_KEY[key]
	if not phrase then
		return key
	end
	local text = phrase.text
	if targetName then
		text = text:gsub("%[P1%]", function()
			return targetName
		end)
	end
	return text
end

return QuickChat
''')
open('/home/claude/frontlines/rules_flow/QuickChat.lua','w').write('\n'.join(L))
