--[[
	Frontlines (working title) - flag index (OpenFront nation flags as raw pixels for EditableImage).
	Copyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.
	Based on OpenFront: © OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO
	Flags © OpenFront, CC BY-SA 4.0 (resources/flags), rasterized to 36x24 by gen_flags.py.
	GENERATED FILE - edit gen_flags.py and re-run it instead of editing this by hand.
]]

-- ReplicatedStorage.Shared.Flags (ModuleScript). Children-free: the pixel data lives in the
-- sibling modules Shared.FlagsData1..N (a script Source is limited to 200,000 characters).
-- Flags.WIDTH, Flags.HEIGHT, Flags.CREDIT, Flags.has(code), Flags.get(code) -> base64 RGBA?
-- Codes are the "flag" field of each nation in Shared.MapCatalog. Clients draw them with
-- StarterPlayerScripts.FlagKit.

local Shared = script.Parent

local Flags = {}
Flags.WIDTH = 36
Flags.HEIGHT = 24
Flags.CREDIT = "Flags © OpenFront, CC BY-SA 4.0"

-- code -> chunk index
local INDEX = {
	["Alabama"] = 1,
	["Alaska"] = 1,
	["Arizona"] = 1,
	["Arkansas"] = 1,
	["California"] = 1,
	["Colorado"] = 1,
	["Connecticut"] = 1,
	["Delaware"] = 1,
	["District_of_Columbia"] = 1,
	["Duchy of Modena and Reggio"] = 1,
	["Duchy of Parma"] = 1,
	["Florida"] = 1,
	["Georgia_US"] = 1,
	["Grand Duchy of Tuscany"] = 1,
	["Habsburg Austria"] = 1,
	["Hawaii"] = 1,
	["Idaho"] = 1,
	["Illinois"] = 1,
	["Indiana"] = 1,
	["Iowa"] = 1,
	["Kansas"] = 1,
	["Kentucky"] = 1,
	["Kingdom of Hungary"] = 1,
	["Kingdom of Sardinia"] = 1,
	["Louisiana"] = 1,
	["Maine"] = 1,
	["Maryland"] = 1,
	["Massachusetts"] = 1,
	["Michigan"] = 1,
	["Minnesota"] = 1,
	["Mississippi"] = 1,
	["Missouri"] = 1,
	["Montana"] = 1,
	["Nebraska"] = 1,
	["Nevada"] = 1,
	["New_Hampshire"] = 1,
	["New_Jersey"] = 1,
	["New_Mexico"] = 1,
	["New_York"] = 1,
	["North_Carolina"] = 2,
	["North_Dakota"] = 2,
	["Nunavut"] = 2,
	["Ohio"] = 2,
	["Oklahoma"] = 2,
	["Oregon"] = 2,
	["PapalStates"] = 2,
	["Pennsylvania"] = 2,
	["Quebec"] = 2,
	["Rhode_Island"] = 2,
	["Sami flag"] = 2,
	["Siberia"] = 2,
	["South_Carolina"] = 2,
	["South_Dakota"] = 2,
	["Tennessee"] = 2,
	["Texas"] = 2,
	["TwoSicilies"] = 2,
	["Utah"] = 2,
	["Vermont"] = 2,
	["Virginia"] = 2,
	["Washington"] = 2,
	["West_Virginia"] = 2,
	["Wisconsin"] = 2,
	["Wyoming"] = 2,
	["Yukon"] = 2,
	["ad"] = 2,
	["al"] = 2,
	["alberta"] = 2,
	["ao"] = 2,
	["aq"] = 2,
	["ar"] = 2,
	["at"] = 2,
	["au"] = 2,
	["ba"] = 2,
	["be"] = 2,
	["bg"] = 2,
	["bj"] = 2,
	["bo"] = 2,
	["br"] = 2,
	["britishcolumbia"] = 3,
	["bt"] = 3,
	["bw"] = 3,
	["by"] = 3,
	["ca"] = 3,
	["cd"] = 3,
	["cf"] = 3,
	["ch"] = 3,
	["cn"] = 3,
	["co"] = 3,
	["cu"] = 3,
	["cv"] = 3,
	["cy"] = 3,
	["cz"] = 3,
	["de"] = 3,
	["dk"] = 3,
	["do"] = 3,
	["dz"] = 3,
	["ee"] = 3,
	["eg"] = 3,
	["es"] = 3,
	["et"] = 3,
	["fi"] = 3,
	["fr"] = 3,
	["ga"] = 3,
	["gb"] = 3,
	["gb-eng"] = 3,
	["gb-sct"] = 3,
	["gb-wls"] = 3,
	["ge"] = 3,
	["gl"] = 3,
	["gq"] = 3,
	["gr"] = 3,
	["gt"] = 3,
	["gy"] = 3,
	["hn"] = 3,
	["hr"] = 3,
	["ht"] = 3,
	["hu"] = 3,
	["ic"] = 4,
	["id"] = 4,
	["ie"] = 4,
	["il"] = 4,
	["in"] = 4,
	["iq"] = 4,
	["ir"] = 4,
	["is"] = 4,
	["it"] = 4,
	["jo"] = 4,
	["jp"] = 4,
	["ke"] = 4,
	["km"] = 4,
	["kz"] = 4,
	["lb"] = 4,
	["li"] = 4,
	["lk"] = 4,
	["lr"] = 4,
	["lt"] = 4,
	["lv"] = 4,
	["ly"] = 4,
	["ma"] = 4,
	["manitoba"] = 4,
	["mc"] = 4,
	["mg"] = 4,
	["ml"] = 4,
	["mn"] = 4,
	["mx"] = 4,
	["na"] = 4,
	["ne"] = 4,
	["newbrunswick"] = 4,
	["newfoundlandandlabrador"] = 4,
	["ng"] = 4,
	["ni"] = 4,
	["nl"] = 4,
	["no"] = 4,
	["northern_ireland"] = 4,
	["northwestterritories"] = 4,
	["novascotia"] = 4,
	["nz"] = 5,
	["om"] = 5,
	["ontario"] = 5,
	["pa"] = 5,
	["pe"] = 5,
	["ph"] = 5,
	["pk"] = 5,
	["pl"] = 5,
	["pr"] = 5,
	["princeedwardisland"] = 5,
	["provence"] = 5,
	["pt"] = 5,
	["pt-azores"] = 5,
	["ro"] = 5,
	["rs"] = 5,
	["ru"] = 5,
	["sa"] = 5,
	["saskatchewan"] = 5,
	["sd"] = 5,
	["se"] = 5,
	["sh"] = 5,
	["sh-ac"] = 5,
	["sk"] = 5,
	["sl"] = 5,
	["sm"] = 5,
	["sn"] = 5,
	["so"] = 5,
	["ss"] = 5,
	["st"] = 5,
	["sy"] = 5,
	["td"] = 5,
	["th"] = 5,
	["tn"] = 5,
	["tr"] = 5,
	["tw"] = 5,
	["tz"] = 5,
	["ua"] = 5,
	["us"] = 5,
	["uy"] = 5,
	["ve"] = 6,
	["venice"] = 6,
	["ye"] = 6,
	["yt"] = 6,
	["za"] = 6,
	["zm"] = 6,
	["zw"] = 6,
}

local CHUNKS = 6
local loaded: { [number]: { [string]: string } } = {}

function Flags.has(code: string): boolean
	return INDEX[code] ~= nil
end

function Flags.get(code: string): string?
	local i = INDEX[code]
	if not i or i > CHUNKS then
		return nil
	end
	if not loaded[i] then
		local mod = Shared:WaitForChild("FlagsData" .. i, 10)
		if not mod then
			return nil
		end
		loaded[i] = require(mod) :: any
	end
	return loaded[i][code]
end

return Flags
