--[[
	War Front - quick chat phrase list (shared by server validation and client menus).
	Copyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.
	Based on OpenFront: © OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO
	Phrases from OpenFront resources/QuickChat.json + resources/lang/en.json, CC BY-SA 4.0.
	Modified version re-implemented in Luau for Roblox; not affiliated with or endorsed by OpenFront.
]]

-- ReplicatedStorage.Shared.QuickChat (ModuleScript). GENERATED by gen_quickchat.py.
-- A phrase key is "<category>.<key>" (e.g. "help.troops"), exactly OpenFront's quickChatKey.
-- Phrases with requiresPlayer = true contain "[P1]", replaced by the chosen target player's name.
-- Client -> server: net:FireServer("quickChat", recipientId, phraseKey, targetId?)
-- Server -> sender and recipient: "quickChat" { from, to, key, target? }
-- Display (EventsDisplay.onDisplayChatEvent): recipient sees QuickChat.FROM, sender QuickChat.TO.

local QuickChat = {}

QuickChat.TITLE = "Quick Chat"
QuickChat.FROM = "From {user}: {msg}" -- {user}, {msg}
QuickChat.TO = "Sent {user}: {msg}" -- {user}, {msg}
QuickChat.COOLDOWN_TICKS = 30 -- Config.quickChatCooldown(): 3 s per recipient

-- Categories in OpenFront's menu order, with their phrases in order.
QuickChat.CATEGORIES = {
	{
		key = "help",
		name = "Help",
		phrases = {
			{ key = "help.troops", text = "Please give me troops!", requiresPlayer = false },
			{ key = "help.troops_frontlines", text = "Send troops to the frontlines!", requiresPlayer = false },
			{ key = "help.gold", text = "Please give me gold!", requiresPlayer = false },
			{ key = "help.no_attack", text = "Please don't attack me!", requiresPlayer = false },
			{ key = "help.sorry_attack", text = "Sorry, I didn’t mean to attack.", requiresPlayer = false },
			{ key = "help.alliance", text = "Alliance?", requiresPlayer = false },
			{ key = "help.help_defend", text = "Help me defend against [P1]!", requiresPlayer = true },
			{ key = "help.trade_partners", text = "Let's be trade partners!", requiresPlayer = false },
		},
	},
	{
		key = "attack",
		name = "Attack",
		phrases = {
			{ key = "attack.attack", text = "Attack [P1]!", requiresPlayer = true },
			{ key = "attack.mirv", text = "Launch a MIRV at [P1]!", requiresPlayer = true },
			{ key = "attack.focus", text = "Focus fire on [P1]!", requiresPlayer = true },
			{ key = "attack.finish", text = "Let's finish off [P1]!", requiresPlayer = true },
			{ key = "attack.build_warships", text = "Build Warships!", requiresPlayer = false },
		},
	},
	{
		key = "defend",
		name = "Defend",
		phrases = {
			{ key = "defend.defend", text = "Defend [P1]!", requiresPlayer = true },
			{ key = "defend.defend_from", text = "Defend from [P1]!", requiresPlayer = true },
			{ key = "defend.dont_attack", text = "Don’t attack [P1]!", requiresPlayer = true },
			{ key = "defend.ally", text = "[P1] is my ally!", requiresPlayer = true },
			{ key = "defend.build_posts", text = "Build Defense Posts!", requiresPlayer = false },
		},
	},
	{
		key = "greet",
		name = "Greetings",
		phrases = {
			{ key = "greet.hello", text = "Hello!", requiresPlayer = false },
			{ key = "greet.good_job", text = "Good job!", requiresPlayer = false },
			{ key = "greet.good_luck", text = "Good luck!", requiresPlayer = false },
			{ key = "greet.have_fun", text = "Have fun!", requiresPlayer = false },
			{ key = "greet.gg", text = "GG!", requiresPlayer = false },
			{ key = "greet.nice_to_meet", text = "Nice to meet you!", requiresPlayer = false },
			{ key = "greet.well_played", text = "Well played!", requiresPlayer = false },
			{ key = "greet.hi_again", text = "Hi again!", requiresPlayer = false },
			{ key = "greet.bye", text = "Bye!", requiresPlayer = false },
			{ key = "greet.thanks", text = "Thanks!", requiresPlayer = false },
			{ key = "greet.oops", text = "Oops, wrong button!", requiresPlayer = false },
			{ key = "greet.trust_me", text = "You can trust me. Promise!", requiresPlayer = false },
			{ key = "greet.trust_broken", text = "I trusted you...", requiresPlayer = false },
			{ key = "greet.ruining_games", text = "You're ruining both of our games.", requiresPlayer = false },
			{ key = "greet.dont_do_that", text = "Don't do that!", requiresPlayer = false },
			{ key = "greet.same_team", text = "I'm on your side!", requiresPlayer = false },
		},
	},
	{
		key = "misc",
		name = "Miscellaneous",
		phrases = {
			{ key = "misc.go", text = "Let’s go!", requiresPlayer = false },
			{ key = "misc.strategy", text = "Nice strategy!", requiresPlayer = false },
			{ key = "misc.fun", text = "This game is fun!", requiresPlayer = false },
			{ key = "misc.team_up", text = "Let’s team up against [P1]!", requiresPlayer = true },
			{ key = "misc.pr", text = "When will my PR finally get merged...?", requiresPlayer = false },
			{ key = "misc.build_closer", text = "Build closer to get trains!", requiresPlayer = false },
			{ key = "misc.coastline", text = "Please let me get a coastline.", requiresPlayer = false },
		},
	},
	{
		key = "warnings",
		name = "Warnings",
		phrases = {
			{ key = "warnings.strong", text = "[P1] is strong.", requiresPlayer = true },
			{ key = "warnings.weak", text = "[P1] is weak.", requiresPlayer = true },
			{ key = "warnings.mirv_soon", text = "[P1] can launch a MIRV soon!", requiresPlayer = true },
			{ key = "warnings.number1_warning", text = "The #1 player will win soon unless we team up!", requiresPlayer = false },
			{ key = "warnings.stalemate", text = "Let's make peace. This is a stalemate, we will both lose.", requiresPlayer = false },
			{ key = "warnings.has_allies", text = "[P1] has many allies.", requiresPlayer = true },
			{ key = "warnings.no_allies", text = "[P1] has no allies.", requiresPlayer = true },
			{ key = "warnings.betrayed", text = "[P1] betrayed their ally!", requiresPlayer = true },
			{ key = "warnings.betrayed_me", text = "[P1] betrayed me!", requiresPlayer = true },
			{ key = "warnings.getting_big", text = "[P1] is growing too fast!", requiresPlayer = true },
			{ key = "warnings.danger_base", text = "[P1] is unprotected!", requiresPlayer = true },
			{ key = "warnings.saving_for_mirv", text = "[P1] is saving up to launch a MIRV.", requiresPlayer = true },
			{ key = "warnings.mirv_ready", text = "[P1] has enough gold to launch a MIRV!", requiresPlayer = true },
			{ key = "warnings.snowballing", text = "[P1] is snowballing too fast!", requiresPlayer = true },
			{ key = "warnings.cheating", text = "[P1] is cheating!", requiresPlayer = true },
			{ key = "warnings.stop_trading", text = "Stop trading with [P1]!", requiresPlayer = true },
			{ key = "warnings.stop_trading_all", text = "Please stop trading with all!", requiresPlayer = false },
		},
	},
}

-- Flat lookup: phraseKey -> phrase entry.
QuickChat.BY_KEY = {}
for _, cat in QuickChat.CATEGORIES do
	for _, phrase in cat.phrases do
		QuickChat.BY_KEY[phrase.key] = phrase
	end
end

-- English text for a phrase key, with [P1] replaced by targetName.
function QuickChat.text(key: string, targetName: string?): string
	local phrase = QuickChat.BY_KEY[key]
	if not phrase then
		return key
	end
	local text = phrase.text
	if targetName then
		text = text:gsub("%[P1%]", function()
			return targetName
		end)
	end
	return text
end

return QuickChat
