--[[
	War Front - tribe (bot) name generator.
	Copyright (C) 2026 Liam (lacedsc3ne). Licensed under the GNU AGPL v3 or later.
	Based on OpenFront: © OpenFront and Contributors - https://github.com/openfrontio/OpenFrontIO
	Name lists from OpenFront resources/tribeNameThemes.json, © OpenFront and Contributors, CC BY-SA 4.0.
	Modified version re-implemented in Luau for Roblox; not affiliated with or endorsed by OpenFront.
]]

-- ServerScriptService.TribeNames (ModuleScript). GENERATED by gen_tribes.py from OpenFront's
-- tribeNameThemes.json and each map's info.json "themes" (TribeSpawner.ts / utils/TribeNames.ts):
-- a tribe is named "<prefix> <suffix>" from the merged themes of the map (default theme if none).

local TribeNames = {}

-- map folder (MapCatalog .folder) -> theme keys
local MAP_THEMES = {
	europe = { "europe" },
	world = { "default" },
	africa = { "africa" },
	northamerica = { "north_america" },
	unitedstates = { "north_america" },
	alps = { "europe" },
	britannia = { "europe" },
	italia = { "europe" },
}

local THEMES = {
	africa = {
		prefixes = {
			"Egyptian", "Nubian", "Kushite", "Aksumite", "Ethiopian", "Songhai", "Malian", "Ghanaian",
			"Benin", "Ashanti", "Zulu", "Tuareg", "Berber", "Kanem-Bornu", "Buganda", "Mossi", "Swahili",
			"Somali", "Wolof", "Yoruba", "Igbo", "Hausa", "Fulani", "Maasai", "Kikuyu", "Shona", "Luba",
			"Lunda", "Kongo", "Lozi", "Tswana", "Sotho", "Xhosa", "Rwandan", "Burundian", "Baganda",
			"Bamileke", "Fang", "San", "Khoikhoi", "Merina", "Sakalava", "Betsileo", "Matabele", "Rozvi",
			"Mutapa",
		},
		suffixes = {
			"Empire", "Kingdom", "Sultanate", "Caliphate", "Dynasty", "Chiefdom", "Confederation",
			"Republic", "State", "Territory", "Province", "Region", "Nation", "Tribe", "Clan", "Alliance",
			"League", "Council", "Assembly", "Federation", "Union", "Dominion", "Realm", "Colony",
			"Protectorate",
		},
	},
	default = {
		prefixes = {
			"Akkadian", "Babylonian", "Sumerian", "Hittite", "Phoenician", "Canaanite", "Minoan",
			"Mycenaean", "Etruscan", "Scythian", "Thracian", "Dacian", "Illyrian", "Median", "Chaldean",
			"Roman", "Greek", "Byzantine", "Persian", "Parthian", "Seleucid", "Ptolemaic", "Palmyrene",
			"Macedonian", "Carthaginian", "Ming", "Tang", "Song", "Yuan", "Mauryan", "Kushan", "Rajput",
			"Mughal", "Satavahana", "Vijayanagara", "Egyptian", "Nubian", "Kushite", "Aksumite",
			"Ethiopian", "Songhai", "Malian", "Ghanaian", "Benin", "Ashanti", "Zulu", "Tuareg", "Berber",
			"Kanem-Bornu", "Buganda", "Mossi", "Swahili", "Somali", "Wolof", "Umayyad", "Abbasid",
			"Ayyubid", "Fatimid", "Mamluk", "Seljuk", "Safavid", "Ottoman", "Almoravid", "Almohad",
			"Rashidun", "Ziyarid", "Frankish", "Visigothic", "Ostrogothic", "Viking", "Norman", "Saxon",
			"Anglo-Saxon", "Celtic", "Gaulish", "Carolingian", "Merovingian", "Capetian", "Plantagenet",
			"Tudor", "Stuart", "Habsburg", "Romanov", "Lancaster", "York", "Bourbon", "Napoleonic",
			"British", "French", "Spanish", "Portuguese", "Dutch", "Russian", "German", "Italian",
			"Swedish", "Norwegian", "Danish", "Polish", "Hungarian", "Austrian", "Swiss", "Czech", "Slovak",
			"Serbian", "Croatian", "Bosnian", "Montenegrin", "Bulgarian", "Romanian", "Apache", "Sioux",
			"Cherokee", "Navajo", "Iroquois", "Inuit", "Arawak", "Carib", "Taino", "Aztec", "Mayan",
			"Incan", "Mapuche", "Guarani", "Tupi", "Yanomami", "Zuni", "Hopi", "Kiowa", "Comanche",
			"Shoshone", "Japanese", "Ryukyu", "Ainu", "Cham", "Khmer", "Thai", "Vietnamese", "Burmese",
			"Balinese", "Malay", "Filipino", "Mongolian", "Korean", "Tibetan", "Manchu", "Uyghur", "Hmong",
			"Karen", "Pyu", "Hawaiian", "Fijian", "Tongan", "Samoan", "Maori", "Micronesian", "Hebrew",
			"Armenian", "Circassian", "Georgian", "Kurdish", "Turkic", "Kazakh", "Uzbek", "Kyrgyz", "Tajik",
			"Pashtun", "Baloch", "Afghan", "Kenyan", "Ugandan", "Bhutanese", "Latin", "Moldovan",
			"Militant", "Spartan",
		},
		suffixes = {
			"Empire", "Dynasty", "Kingdom", "Queendom", "Sultanate", "Confederation", "Union", "Republic",
			"Caliphate", "Dominion", "Realm", "State", "Federation", "Territory", "Commonwealth", "League",
			"Duchy", "Province", "Protectorate", "Colony", "Mandate", "Free State", "Canton", "Region",
			"Nation", "Assembly", "Hierarchy", "Archduchy", "Grand Duchy", "Metropolis", "Cluster",
			"Alliance", "Tribunal", "Council", "Confederacy", "Order", "Regime", "Syndicate", "Guild",
			"Corporation", "Patriarchy", "Matriarchy", "Legion", "Horde", "Clan", "Brotherhood",
			"Sisterhood", "Ascendancy", "Supremacy", "Tribe", "Army", "Dictatorship", "Country",
			"Oligarchy", "Monkdom", "Throng", "Host", "Area", "District", "Fief", "Wilderness",
			"Settlement", "Parliament", "Anarchy", "Democracy", "Autocracy",
		},
	},
	europe = {
		prefixes = {
			"Roman", "Greek", "Byzantine", "Frankish", "Visigothic", "Ostrogothic", "Viking", "Norman",
			"Saxon", "Anglo-Saxon", "Celtic", "Gaulish", "Carolingian", "Merovingian", "Capetian",
			"Plantagenet", "Tudor", "Stuart", "Habsburg", "Romanov", "Lancaster", "York", "Bourbon",
			"Napoleonic", "British", "French", "Spanish", "Portuguese", "Dutch", "Russian", "German",
			"Italian", "Swedish", "Norwegian", "Danish", "Polish", "Hungarian", "Austrian", "Swiss",
			"Czech", "Slovak", "Serbian", "Croatian", "Bosnian", "Montenegrin", "Bulgarian", "Romanian",
			"Finnish", "Estonian", "Latvian", "Lithuanian", "Irish", "Scottish", "Welsh", "Basque",
			"Galician", "Sardinian", "Sicilian", "Venetian", "Florentine", "Genoese", "Milanese",
			"Prussian", "Bavarian", "Teutonic", "Knights Templar", "Crusader", "Papal", "Holy Roman",
		},
		suffixes = {
			"Kingdom", "Empire", "Republic", "Duchy", "Grand Duchy", "Archduchy", "County", "Principality",
			"Barony", "Lordship", "March", "Shire", "Fief", "Realm", "Dominion", "Crown", "Dynasty",
			"House", "Order", "League", "Confederation", "Alliance", "Pact", "Union", "Federation",
			"Commonwealth", "State", "Nation", "Province", "Territory",
		},
	},
	north_america = {
		prefixes = {
			"Apache", "Sioux", "Cherokee", "Navajo", "Iroquois", "Inuit", "Arawak", "Carib", "Taino",
			"Aztec", "Mayan", "Zuni", "Hopi", "Kiowa", "Comanche", "Shoshone", "Cree", "Ojibwe", "Seminole",
			"Cheyenne", "Pawnee", "Mohawk", "Huron", "Tlingit", "Haida", "Nez Perce", "Crow", "Blackfoot",
			"Pueblo", "Mi'kmaq", "Algonquin", "Wampanoag", "Potawatomi", "Shawnee", "Chickasaw", "Choctaw",
			"Creek", "Canadian", "American", "Mexican", "Texan", "Californian", "Quebecois", "Acadian",
			"Louisianan", "Appalachian", "Yankee", "Frontiersman",
		},
		suffixes = {
			"Nation", "Confederation", "Territory", "Federation", "Republic", "State", "Province", "Colony",
			"Commonwealth", "Dominion", "Council", "Assembly", "Tribe", "Clan", "League", "Alliance",
			"Union", "Band", "Settlement", "Frontier", "Range", "Heartland", "Homeland", "Territories",
		},
	},
}

-- Returns a function that yields a new tribe name each call (random prefix + suffix, like
-- TribeSpawner.randomTribeName with no custom tribes). `folder` is the map's MapCatalog folder.
function TribeNames.picker(folder: string?, rng: Random): () -> string
	local keys = (folder and MAP_THEMES[folder]) or { "default" }
	local prefixes, suffixes = {}, {}
	for _, key in keys do
		local theme = THEMES[key]
		if theme then
			table.move(theme.prefixes, 1, #theme.prefixes, #prefixes + 1, prefixes)
			table.move(theme.suffixes, 1, #theme.suffixes, #suffixes + 1, suffixes)
		end
	end
	if #prefixes == 0 or #suffixes == 0 then
		prefixes, suffixes = THEMES.default.prefixes, THEMES.default.suffixes
	end
	return function(): string
		return prefixes[rng:NextInteger(1, #prefixes)] .. " " .. suffixes[rng:NextInteger(1, #suffixes)]
	end
end

return TribeNames
